### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SpazzMarticus** [KaiBelmo/portfolio-win95#2]
There is a typo in the notepad menu. "search" is spelled "seach":

https://github.com/KaiBelmo/kai-belmo/blob/aecf4f1973df184d4ad63e230d04ea3dd4cbeb2b/src/components/apps/notepad.vue#L34

**Comment by KaiBelmo** [comment]
thanks!

**Comment by KaiBelmo** [comment]
fixed: https://github.com/KaiBelmo/kai-belmo/commit/ea37529353f2191b1e548bb383ba6896740870a2
